services:
  vigia:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - /home/coolify-admin/vigia:/usr/share/nginx/html:ro
    networks:
      - coolify
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
      - traefik.http.routers.vigia-http.entrypoints=http
      - traefik.http.routers.vigia-http.rule=Host(`vigia.ppotools.net`)
      - traefik.http.routers.vigia-http.middlewares=https-redir@docker
      - traefik.http.routers.vigia.entrypoints=https
      - traefik.http.routers.vigia.rule=Host(`vigia.ppotools.net`)
      - traefik.http.routers.vigia.tls=true
      - traefik.http.routers.vigia.tls.certresolver=letsencrypt
      - traefik.http.routers.vigia.middlewares=authelia@docker
      - traefik.http.routers.vigia.service=vigia
      - traefik.http.services.vigia.loadbalancer.server.port=80

networks:
  coolify:
    external: true
    name: coolify
